import { ContextLoader } from "./(components)/contexts/ContextLoader";
import { Footer } from "./(components)/footer/page";
import "./style/_main.scss";

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default async function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang="en">
			<body>
				<ContextLoader>
					{children}
					<Footer />
				</ContextLoader>
			</body>
		</html>
	);
}
